### ISSUE TITLE
Error when batch size=1

### ISSUE THREAD

**Issue by Guocode** [MengHao666/Hand-BMC-pytorch#2]
File "/data_sdc/gzh/tmp/neural_render_learn/losses/BMC_loss.py", line 355, in <module>
    loss_total, loss_dict = bmc.compute_loss(joints)
  File "/data_sdc/gzh/tmp/neural_render_learn/losses/BMC_loss.py", line 326, in compute_loss
    TIP_X_axis = torch.matmul(temp_R, DIP_X_axis.unsqueeze(3)).squeeze()
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

**Comment by MengHao666** [comment]
@Guocode 
Hi, I might overlook some details when I wote this code 5 months ago.
An ugly but work solution is that u can add this 3 lines after[ line 338](https://github.com/MengHao666/Hand-BMC-pytorch/blob/d9d1a5394ebc84079e9fc25885122c18a9ec1505/weakloss.py#L338) as follows:


    if batch_size==1:
        DIP_X_axis=DIP_X_axis[np.newaxis,]
        DIP_Y_axis=DIP_Y_axis[np.newaxis,]

    TIP_X_axis = torch.matmul(temp_R, DIP_X_axis.unsqueeze(3)).squeeze()
    TIP_Y_axis = torch.matmul(temp_R, DIP_Y_axis.unsqueeze(3)).squeeze()
    TIP_bones_xz = TIP_bones - inner_product(TIP_bones, TIP_Y_axis).unsqueeze(2) * TIP_Y_axis
