### ISSUE TITLE
Can't find the rdp algorithm

### ISSUE THREAD

**Issue by LiuYi-Up** [MengHao666/Hand-BMC-pytorch#3]
Hello,thank you for your sharing. When I run the 'python calculate_convex_hull.py', it could't find the 'rdp' module. Thus it will be very greatfull if you can help this.

**Comment by MengHao666** [comment]
please see [here](https://github.com/MengHao666/Hand-BMC-pytorch/blob/d9d1a5394ebc84079e9fc25885122c18a9ec1505/environment.yml#L75)，and u can use `pip ` to install it.
