### ISSUE TITLE
Normalizing bone length by Reference Bone Length

### ISSUE THREAD

**Issue by thiagomcoutinho** [MengHao666/Hand-BMC-pytorch#4]
Hi @MengHao666 , first of all thank you for your implementation.

I have a doubt with relation to the reference bone normalization in the BMCLoss Class. When you compute the min and max values for the bone lengths in the **calculate_bmc.py** code, all bones are normalized by the reference bone, as shown below:

https://github.com/MengHao666/Hand-BMC-pytorch/blob/d9d1a5394ebc84079e9fc25885122c18a9ec1505/calculate_bmc.py#L50-L57

But in the **BMCLoss Class** this step is not made, which could generate wrong results if the input data isn't normalized. Is this right?

https://github.com/MengHao666/Hand-BMC-pytorch/blob/d9d1a5394ebc84079e9fc25885122c18a9ec1505/weakloss.py#L253-L278

Also, did you think what is the easiest way to use the algorithm for the left hand? 

Thanks in advance.

**Comment by MengHao666** [comment]
> h relation to the reference bone normalization in the BMCLoss Class. When you compute the min and max values for the bone lengths in the **calculate_bmc.py** code, all bones are normalized by the reference bone, as shown below:

Sure. But as we have strong supervision of 3D groundtruth joint  location, I guess this effect is very small. You might do an ablation study to see further.
